### ISSUE TITLE
Create initial look and feel for edgenative.eclipse.org

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/edgenative.eclipse.org#1]
Since we are running on time (we need something  on prod by the end of this week), the plan is to create a very basic website based off the work we did for https://www.openhwgroup.org/ but with different colors, font and images.

The initial website will have 2 pages, the homepage and a FAQ page.

We plan on having the same number of sections on the homepage but with a slight variation on the content.

### Homepage sections:

- Jumbotron
- News and Events
- Mission Statement
- Our Founding Members
- Testimonials
- FAQ teaser
- Featured footer for promoting slack workspace and mailing list.

I created a basic website based off our Eclipse Foundation Hugo theme that we should now customize with the help of our designer, @ChristieWittEclipse:
https://eclipsefdn-edgenative.netlify.com/

![Screen Shot 2019-12-05 at 11 22 12 AM](https://user-images.githubusercontent.com/893942/70253609-8044be00-1751-11ea-846b-5261099a8885.png)

Let's start by defining the following:

## Color pallette: 
- @brand-primary:         #f7941e; // Orange
- @brand-secondary:    #404040; // Gray
- @brand-tertiary:          #3f7b96; // Blue
- @brand-quaternary:   #efefef; // Light Gray 
- @brand-quinary:         @brand-quaternary; // Light Gray (Breadcrumbs)
- @brand-info:            @brand-tertiary;
- @brand-info-light:     lighten(@brand-info, 20%);
- @brand-warning:      @brand-primary;

* These are currently the colors of the Eclipse Foundation website. We should change them!

## Default Styles
- Headings
- font

## Branding
- SVG Logo:
- Social media image: 
- Favicon: 

## Graphics/Images
- Jumbotron background & styles
- Mission statement section background & styles
- Testimonials section background & styles
- FAQ section background & styles
- Join our mailing list section background & styles

**Comment by ChristieWittEclipse** [comment]
Updated info below:

**Color palette:**
@brand-primary: #396894; // Blue
@brand-secondary: #5997BD; // Light Blue
@brand-tertiary: #213970; // Dark Blue
@brand-quaternary: #efefef; // Light Gray
@brand-quinary: @brand-quaternary; // Light Gray (Breadcrumbs)
@brand-info: @brand-tertiary;
@brand-info-light: lighten(@brand-info, 20%);
@brand-warning: @brand-primary;

**Default Styles**
Headings: Pragmactica Bold, same font size as current template
font: Pragmatica regular

**Branding** 
**Graphics/Images**
(See attached .zip)
[Edge Web Assets.zip](https://github.com/EclipseFdn/edgenative.eclipse.org/files/3928353/Edge.Web.Assets.zip)

**Comment by chrisguindon** [comment]
@ChristieWittEclipse The Pragmatica font is not available from google fonts:
https://fonts.google.com/?query=Pragmatica

It's listed on the site but we would need to buy a license where we would be allowed to include it in the git repository: https://www.fonts.com/font/paratype/pragmatica?QueryFontType=Web&src=GoogleWebFonts 

Is there a similar font that we can use via google fonts?

We are currently using:
https://fonts.google.com/specimen/Libre+Franklin


```
//== Typography
@font-family-sans-serif:  "Libre Franklin", "Helvetica Neue", Helvetica, Arial, sans-serif;
```

**Comment by ChristieWittEclipse** [comment]
Please use Roboto instead:
[(https://fonts.google.com/specimen/Roboto)]

**Comment by chrisguindon** [comment]
@ChristieWittEclipse I am noticing that the images are quite big in size!

Is it possible to optimize them for web?

**Comment by ChristieWittEclipse** [comment]
Please see compressed graphics below:
[compressed-graphics.zip](https://github.com/EclipseFdn/edgenative.eclipse.org/files/3929213/compressed-graphics.zip)

**Comment by chrisguindon** [comment]
We now have a website! 

https://edgenative.eclipse.org/

Thank you @ChristieWittEclipse for helping us to get this done  on time!
