### ISSUE TITLE
Improve accessibility (contrast) on Edge Native website

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/edgenative.eclipse.org#12]
As mentioned in https://github.com/EclipseFdn/edgenative.eclipse.org/pull/7#issuecomment-563608351, we do have some accessibility issues that we need to solve with the new design.

For example, the hamburger menu is barely visible in some screen size.

![Screen Shot 2019-12-10 at 10 48 21 AM](https://user-images.githubusercontent.com/893942/70544870-c5466700-1b3a-11ea-9934-c4d3a2d4d0bf.png)

@ChristieWittEclipse, could you post some recommendations to help us improve the contrast on the site.

**Comment by chrisguindon** [comment]
Thanks @ChristieWittEclipse!

+1 for your recommendations but please note that the favicon is already pink: 
https://edgenative.eclipse.org/images/edgenative/favicon/favicon.ico

Your browser probably has the old one cached.

**Comment by ChristieWittEclipse** [comment]
@chrisguindon perfect! It was cached.

**Comment by chrisguindon** [comment]
Thank you @autumnfound and @ChristieWittEclipse
