### ISSUE TITLE
Logos associated with the working group must include "tm"

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/edgenative.eclipse.org#16]
All logos associated with the working group should have a "tm" on them somewhere to indicate that they are trademarks of the Eclipse Foundation.

**Comment by ChristieWittEclipse** [comment]
I haven't forgotten about this @waynebeaton, I just sent a few questions to Sharon and cc'd you before implementation of the TM.

**Comment by ChristieWittEclipse** [comment]
@waynebeaton I'm closing this ticket for now as Sharon mentioned mentioned that the policies surrounding working group trademark use has not really been clearly defined yet. This will be a part of a larger project in the new year.
