### ISSUE TITLE
Add under events

### ISSUE THREAD

**Issue by ltran016** [EclipseFdn/edgenative.eclipse.org#18]
Bosch ConnectedWorld
Feb 9-10, 2020
Berlin, Germany
https://bosch-connected-world.com/attend/

KubeCon Europe
Mar 30-Apr 2
Amsterdam, The Netherlands
https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/

IoT World
Apr 6-9, 2020
San Jose, CA
https://tmt.knect365.com/iot-world/

Huawei Developer Conference
Aug 9-11, 2020
Songshan Lake, China
https://consumer.huawei.com/en/event/hdc2019/

**Comment by autumnfound** [comment]
This is live!

**Comment by ltran016** [comment]
The Huawei date and links are wrong & events need to be in chronological order!

Please change to:

Bosch ConnectedWorld
Feb 9-10, 2020 | Berlin, Germany
https://bosch-connected-world.com/attend/

Huawei Developer Conference
Feb 11-12, 2020 | Shenzhen, China
https://www.huaweicloud.com/HDC.Cloud.html

KubeCon Europe
March 30 - April 2, 2020 | Amsterdam, The Netherlands
https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/

IoT World
Apr 6-9, 2020 | San Jose, CA
https://tmt.knect365.com/iot-world/

**Comment by chrisguindon** [comment]
@autumnfound can you look at fixing the date for the Huawei Developer Conference?

Also, we should look at fixing the order. This is also being track via issue #22

**Comment by autumnfound** [comment]
Fixed! Apologies for the mixup!
