### ISSUE TITLE
News item: 2020 IoT developer survey - ubuntu

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/edgenative.eclipse.org#51]
**News item**
date = "2020-05-20"
title = "The Eclipse 2020 IoT developer survey is live"
link = "https://ubuntu.com/blog/eclipse-2020-iot-developer-survey-is-live"
description = "The IoT Developer Survey, by The Eclipse Foundation, is the industry’s largest developer survey. These surveys centralise useful, high-level information about the IoT industry."

**Comment by autumnfound** [comment]
We've made the sparkplug update to use newsroom data, so you should be able to update newsroom for this news item without going through Github! Let me know if there are any issues with this!

**Comment by shanda-eclipse** [comment]
It's live. Thanks
