### ISSUE TITLE
undefined, undefined NaN, NaN - aN:aN

### ISSUE THREAD

**Issue by joespeed** [EclipseFdn/edgenative.eclipse.org#54]
https://edgenative.eclipse.org

Safari 13.1, macOS 10.15.4 

"undefined, undefined NaN, NaN - aN:aN"
<img width="559" alt="image" src="https://user-images.githubusercontent.com/8238588/82908746-45ac2900-9f1d-11ea-9e74-8d14c18cc56e.png">

**Comment by autumnfound** [comment]
Hi @joespeed! We've seen this crop up across a few of our sites, and you can see our current state at EclipseFdn/jquery-eclipsefdn-api#17. I've submitted a patch today, and we're hoping that we can apply this fix across the Hugo sites in the next couple of days!

**Comment by chrisguindon** [comment]
This should be fixed now on edgenative.eclipse.org!

Thanks for the repo @joespeed
