### ISSUE TITLE
Add Simple Matter to the Edge Native website

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/edgenative.eclipse.org#68]
Please add Si
![download](https://user-images.githubusercontent.com/50374570/100897502-bebca800-348d-11eb-9fed-4111b9336132.png)
mple Matter as a Silver member to the Edge Native website

Thank you,
Zahra

**Comment by flora8984461** [comment]
@ZahraFazli Hello Zahra,
There is no Silver member level on Edge Native website, do you think it's good just to add to funding members like this preview: https://deploy-preview-70--eclipsefdn-edgenative.netlify.app/ ?

Thanks!
