### ISSUE TITLE
Updating the Edge Native Logo

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/edgenative.eclipse.org#72]
Please update the attached logo which has been fixed recently with the old one at: https://edgenative.eclipse.org/

![edge-logo-white-horizontal](https://user-images.githubusercontent.com/75500459/103684425-8828f000-4f59-11eb-8f4e-75caab21b27c.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by flora8984461** [comment]
Hi @meKokabi , just hope to confirm, is not the logo on the current site the same as the one you attached? Probably I missed something... 

Thanks!

**Comment by meKokabi** [comment]
https://drive.google.com/drive/folders/1WPZbWJd-l2ytQAWMS0Dl8guajrHOgAoM
Hello there is slight changes on its height which I have been assigned to fix it and here is the new one.

**Comment by flora8984461** [comment]
Hi @meKokabi , 
Is the png file named "edge-logo-white-horizontal.png" I should use, right? 

Thanks!



> https://drive.google.com/drive/folders/1WPZbWJd-l2ytQAWMS0Dl8guajrHOgAoM
> Hello there is slight changes on its height which I have been assigned to fix it and here is the new one.

**Comment by meKokabi** [comment]
Hello,
Thanks for checking. Yes it is an updated version with slight changes on
its height. I have saved it on Share Drive and here is the link to.
https://drive.google.com/drive/folders/1WPZbWJd-l2ytQAWMS0Dl8guajrHOgAoM
Thanks for your help on this,
Best,
Mehrnaz
