### ISSUE TITLE
Add featured story banner to edgenative.eclipse.org homepage

### ISSUE THREAD

**Issue by jph152** [EclipseFdn/edgenative.eclipse.org#77]
We'd like to add a featured story to the Edge Native homepage, similar to what the ECD Tools site has:

![image](https://user-images.githubusercontent.com/69642121/116588676-d89dd200-a8e9-11eb-9d5e-a65eb05c3840.png)

On the right side, can we add the White Paper thumbnail image (attached) and text as follows:

(LOGO)
**Text:** EdgeOps: A New Open Source Vision
**Button:** Download White Paper
![1 ](https://user-images.githubusercontent.com/69642121/116589376-932dd480-a8ea-11eb-8564-b9e779823f6d.png)

**Comment by jph152** [comment]
@linkfang Hi Zhou, will you be able to get to this by Monday? Thanks

**Comment by linkfang** [comment]
Hi @jph152 , yep, I think so.

**Comment by linkfang** [comment]
Hi @jph152 , 

Just would like to confirm if I got everything right.

The featured story will look like this, 
![image](https://user-images.githubusercontent.com/43075439/117328701-e01d2800-ae61-11eb-935c-fcc9365be603.png)

and both the white page thumbnail and the download button will lead user to this page:
https://outreach.eclipse.foundation/edge-computing-edgeops-white-paper

**Comment by linkfang** [comment]
Preview link:
https://deploy-preview-80--eclipsefdn-edgenative.netlify.app

**Comment by jph152** [comment]
Looks great. Thanks, Zhou!
