### ISSUE TITLE
Add survey report to right side of edge native banner

### ISSUE THREAD

**Issue by jph152** [EclipseFdn/edgenative.eclipse.org#81]
<img width="484" alt="Screen Shot 2021-06-08 at 8 46 19 AM" src="https://user-images.githubusercontent.com/69642121/121187379-00138300-c836-11eb-9af2-e09ab3e2fa49.png">

Can we update the right side of the homepage banner with the following:

**Image:** 
![image](https://user-images.githubusercontent.com/69642121/121192923-60f18a00-c83b-11eb-9571-f6ae2fbbd972.png)

**Text:** 2021 IoT & Edge Commercial Adoption Survey

**Button:** Download the Report

**Button link:** https://outreach.eclipse.foundation/iot-edge-commercial-survey

**Comment by linkfang** [comment]
Hi @jph152 , please preview the changes here:
https://deploy-preview-82--eclipsefdn-edgenative.netlify.app/?utm_source=github&utm_campaign=bot_dp

**Comment by autumnfound** [comment]
I would up the width of the laptop to 250. If there are words they may as well be legible! :)

**Comment by jph152** [comment]
Looks good! +1
