### ISSUE TITLE
Change the right side of homepage banner to promote developer survey

### ISSUE THREAD

**Issue by jph152** [EclipseFdn/edgenative.eclipse.org#84]
<img width="361" alt="Screen Shot 2021-09-27 at 4 29 49 PM" src="https://user-images.githubusercontent.com/69642121/134980538-f4eb64b4-a1ef-428d-8c70-5637983cf710.png">

Can we update this section of the banner to the following:

Text: Participate in the survey today!
Button: Complete the Survey
LINK: https://www.surveymonkey.com/r/L7SXQXN
Image: 
![surveyor](https://user-images.githubusercontent.com/69642121/134980809-52b29c30-0f1f-44f8-a574-481eac32bb76.png)

If possible, we'd like this done in the next couple days

**Comment by linkfang** [comment]
Hi @jph152 ,
Please preview the changes here:
https://deploy-preview-85--eclipsefdn-edgenative.netlify.app/

**Comment by jph152** [comment]
Thanks, let me know when it goes live :)

**Comment by linkfang** [comment]
Now it's live!

**Comment by linkfang** [comment]
@jph152 Now it's live!
