### ISSUE TITLE
Embed membership form on edgenative.eclipse.org

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/edgenative.eclipse.org#89]
Similar to https://github.com/EclipseFdn/iot.eclipse.org/issues/666, we would like to embed the contact us form on edgenative.eclipse.org. 

Here is the code to embed the form:

```
<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	region: "na1",
	portalId: "5413615",
	formId: "052af14a-58cd-47e1-9deb-5ab1ba79a83d"
});
</script>
```
CC @hassanjaber98

**Comment by linkfang** [comment]
Hi @shanda-eclipse ,

Please preview the change here:
https://deploy-preview-90--eclipsefdn-edgenative.netlify.app/join-us/

And the "Join" button in the top menu will take user to this new form
https://deploy-preview-90--eclipsefdn-edgenative.netlify.app/

**Comment by shanda-eclipse** [comment]
+1 to go live

**Comment by linkfang** [comment]
The changes are live.

The redirect will be set when existing Embed issues are all done.

**Comment by linkfang** [comment]
The embeded form was live 2 days ago.

Closing this issue as Eric has created this issue to track the redirect setting
https://gitlab.eclipse.org/eclipsefdn/infrazilla/-/issues/433
