### ISSUE TITLE
Nothing listed in the "What's New" section

### ISSUE THREAD

**Issue by drluckyspin** [EclipseFdn/edgenative.eclipse.org#9]
On the newly deployed site, there is nothing listed in the "What's New" section. 

Presumably this should contain something about the launch of the WG.

Also.. when you click through, the section heading is not UPPERCASE

**Comment by chrisguindon** [comment]
It looks like we accidentally included a test news item:
https://edgenative.eclipse.org/categories/announcements/

I will remove this asap for now.

I am also expecting a request from our marketing team tomorrow for posting our first news item on the site.

**Comment by autumnfound** [comment]
@drluckyspin as there are now items under the What's New section, and the test item was removed, are we good to close this?

**Comment by chrisguindon** [comment]
@autumnfound the announcement heading is still lowercase: https://edgenative.eclipse.org/categories/announcements/

This is something we probably want to fix in the base theme.

**Comment by chrisguindon** [comment]
> @autumnfound the announcement heading is still lowercase: https://edgenative.eclipse.org/categories/announcements/
> 
> This is something we probably want to fix in the base theme.

My update to the base theme is now for edgenative.eclipse.org. I think we are done here now!
